/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.piao888.cg.thriftAPI;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-03-21")
public class UserInfo implements org.apache.thrift.TBase<UserInfo, UserInfo._Fields>, java.io.Serializable, Cloneable, Comparable<UserInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("UserInfo");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField CREATER_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("CreaterName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField CREATER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("CreaterId", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField CREATE_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("CreateTime", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField CREATE_ORG_FIELD_DESC = new org.apache.thrift.protocol.TField("CreateOrg", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField CREATE_ORG_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("CreateOrgId", org.apache.thrift.protocol.TType.STRING, (short)6);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new UserInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new UserInfoTupleSchemeFactory();

  public long id; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String CreaterName; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String CreaterId; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String CreateTime; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String CreateOrg; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String CreateOrgId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    CREATER_NAME((short)2, "CreaterName"),
    CREATER_ID((short)3, "CreaterId"),
    CREATE_TIME((short)4, "CreateTime"),
    CREATE_ORG((short)5, "CreateOrg"),
    CREATE_ORG_ID((short)6, "CreateOrgId");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // CREATER_NAME
          return CREATER_NAME;
        case 3: // CREATER_ID
          return CREATER_ID;
        case 4: // CREATE_TIME
          return CREATE_TIME;
        case 5: // CREATE_ORG
          return CREATE_ORG;
        case 6: // CREATE_ORG_ID
          return CREATE_ORG_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.CREATER_NAME, new org.apache.thrift.meta_data.FieldMetaData("CreaterName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CREATER_ID, new org.apache.thrift.meta_data.FieldMetaData("CreaterId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CREATE_TIME, new org.apache.thrift.meta_data.FieldMetaData("CreateTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CREATE_ORG, new org.apache.thrift.meta_data.FieldMetaData("CreateOrg", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CREATE_ORG_ID, new org.apache.thrift.meta_data.FieldMetaData("CreateOrgId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(UserInfo.class, metaDataMap);
  }

  public UserInfo() {
  }

  public UserInfo(
    long id,
    java.lang.String CreaterName,
    java.lang.String CreaterId,
    java.lang.String CreateTime,
    java.lang.String CreateOrg,
    java.lang.String CreateOrgId)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.CreaterName = CreaterName;
    this.CreaterId = CreaterId;
    this.CreateTime = CreateTime;
    this.CreateOrg = CreateOrg;
    this.CreateOrgId = CreateOrgId;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public UserInfo(UserInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    if (other.isSetCreaterName()) {
      this.CreaterName = other.CreaterName;
    }
    if (other.isSetCreaterId()) {
      this.CreaterId = other.CreaterId;
    }
    if (other.isSetCreateTime()) {
      this.CreateTime = other.CreateTime;
    }
    if (other.isSetCreateOrg()) {
      this.CreateOrg = other.CreateOrg;
    }
    if (other.isSetCreateOrgId()) {
      this.CreateOrgId = other.CreateOrgId;
    }
  }

  public UserInfo deepCopy() {
    return new UserInfo(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    this.CreaterName = null;
    this.CreaterId = null;
    this.CreateTime = null;
    this.CreateOrg = null;
    this.CreateOrgId = null;
  }

  public long getId() {
    return this.id;
  }

  public UserInfo setId(long id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getCreaterName() {
    return this.CreaterName;
  }

  public UserInfo setCreaterName(@org.apache.thrift.annotation.Nullable java.lang.String CreaterName) {
    this.CreaterName = CreaterName;
    return this;
  }

  public void unsetCreaterName() {
    this.CreaterName = null;
  }

  /** Returns true if field CreaterName is set (has been assigned a value) and false otherwise */
  public boolean isSetCreaterName() {
    return this.CreaterName != null;
  }

  public void setCreaterNameIsSet(boolean value) {
    if (!value) {
      this.CreaterName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getCreaterId() {
    return this.CreaterId;
  }

  public UserInfo setCreaterId(@org.apache.thrift.annotation.Nullable java.lang.String CreaterId) {
    this.CreaterId = CreaterId;
    return this;
  }

  public void unsetCreaterId() {
    this.CreaterId = null;
  }

  /** Returns true if field CreaterId is set (has been assigned a value) and false otherwise */
  public boolean isSetCreaterId() {
    return this.CreaterId != null;
  }

  public void setCreaterIdIsSet(boolean value) {
    if (!value) {
      this.CreaterId = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getCreateTime() {
    return this.CreateTime;
  }

  public UserInfo setCreateTime(@org.apache.thrift.annotation.Nullable java.lang.String CreateTime) {
    this.CreateTime = CreateTime;
    return this;
  }

  public void unsetCreateTime() {
    this.CreateTime = null;
  }

  /** Returns true if field CreateTime is set (has been assigned a value) and false otherwise */
  public boolean isSetCreateTime() {
    return this.CreateTime != null;
  }

  public void setCreateTimeIsSet(boolean value) {
    if (!value) {
      this.CreateTime = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getCreateOrg() {
    return this.CreateOrg;
  }

  public UserInfo setCreateOrg(@org.apache.thrift.annotation.Nullable java.lang.String CreateOrg) {
    this.CreateOrg = CreateOrg;
    return this;
  }

  public void unsetCreateOrg() {
    this.CreateOrg = null;
  }

  /** Returns true if field CreateOrg is set (has been assigned a value) and false otherwise */
  public boolean isSetCreateOrg() {
    return this.CreateOrg != null;
  }

  public void setCreateOrgIsSet(boolean value) {
    if (!value) {
      this.CreateOrg = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getCreateOrgId() {
    return this.CreateOrgId;
  }

  public UserInfo setCreateOrgId(@org.apache.thrift.annotation.Nullable java.lang.String CreateOrgId) {
    this.CreateOrgId = CreateOrgId;
    return this;
  }

  public void unsetCreateOrgId() {
    this.CreateOrgId = null;
  }

  /** Returns true if field CreateOrgId is set (has been assigned a value) and false otherwise */
  public boolean isSetCreateOrgId() {
    return this.CreateOrgId != null;
  }

  public void setCreateOrgIdIsSet(boolean value) {
    if (!value) {
      this.CreateOrgId = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((java.lang.Long)value);
      }
      break;

    case CREATER_NAME:
      if (value == null) {
        unsetCreaterName();
      } else {
        setCreaterName((java.lang.String)value);
      }
      break;

    case CREATER_ID:
      if (value == null) {
        unsetCreaterId();
      } else {
        setCreaterId((java.lang.String)value);
      }
      break;

    case CREATE_TIME:
      if (value == null) {
        unsetCreateTime();
      } else {
        setCreateTime((java.lang.String)value);
      }
      break;

    case CREATE_ORG:
      if (value == null) {
        unsetCreateOrg();
      } else {
        setCreateOrg((java.lang.String)value);
      }
      break;

    case CREATE_ORG_ID:
      if (value == null) {
        unsetCreateOrgId();
      } else {
        setCreateOrgId((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case CREATER_NAME:
      return getCreaterName();

    case CREATER_ID:
      return getCreaterId();

    case CREATE_TIME:
      return getCreateTime();

    case CREATE_ORG:
      return getCreateOrg();

    case CREATE_ORG_ID:
      return getCreateOrgId();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case CREATER_NAME:
      return isSetCreaterName();
    case CREATER_ID:
      return isSetCreaterId();
    case CREATE_TIME:
      return isSetCreateTime();
    case CREATE_ORG:
      return isSetCreateOrg();
    case CREATE_ORG_ID:
      return isSetCreateOrgId();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof UserInfo)
      return this.equals((UserInfo)that);
    return false;
  }

  public boolean equals(UserInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_CreaterName = true && this.isSetCreaterName();
    boolean that_present_CreaterName = true && that.isSetCreaterName();
    if (this_present_CreaterName || that_present_CreaterName) {
      if (!(this_present_CreaterName && that_present_CreaterName))
        return false;
      if (!this.CreaterName.equals(that.CreaterName))
        return false;
    }

    boolean this_present_CreaterId = true && this.isSetCreaterId();
    boolean that_present_CreaterId = true && that.isSetCreaterId();
    if (this_present_CreaterId || that_present_CreaterId) {
      if (!(this_present_CreaterId && that_present_CreaterId))
        return false;
      if (!this.CreaterId.equals(that.CreaterId))
        return false;
    }

    boolean this_present_CreateTime = true && this.isSetCreateTime();
    boolean that_present_CreateTime = true && that.isSetCreateTime();
    if (this_present_CreateTime || that_present_CreateTime) {
      if (!(this_present_CreateTime && that_present_CreateTime))
        return false;
      if (!this.CreateTime.equals(that.CreateTime))
        return false;
    }

    boolean this_present_CreateOrg = true && this.isSetCreateOrg();
    boolean that_present_CreateOrg = true && that.isSetCreateOrg();
    if (this_present_CreateOrg || that_present_CreateOrg) {
      if (!(this_present_CreateOrg && that_present_CreateOrg))
        return false;
      if (!this.CreateOrg.equals(that.CreateOrg))
        return false;
    }

    boolean this_present_CreateOrgId = true && this.isSetCreateOrgId();
    boolean that_present_CreateOrgId = true && that.isSetCreateOrgId();
    if (this_present_CreateOrgId || that_present_CreateOrgId) {
      if (!(this_present_CreateOrgId && that_present_CreateOrgId))
        return false;
      if (!this.CreateOrgId.equals(that.CreateOrgId))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(id);

    hashCode = hashCode * 8191 + ((isSetCreaterName()) ? 131071 : 524287);
    if (isSetCreaterName())
      hashCode = hashCode * 8191 + CreaterName.hashCode();

    hashCode = hashCode * 8191 + ((isSetCreaterId()) ? 131071 : 524287);
    if (isSetCreaterId())
      hashCode = hashCode * 8191 + CreaterId.hashCode();

    hashCode = hashCode * 8191 + ((isSetCreateTime()) ? 131071 : 524287);
    if (isSetCreateTime())
      hashCode = hashCode * 8191 + CreateTime.hashCode();

    hashCode = hashCode * 8191 + ((isSetCreateOrg()) ? 131071 : 524287);
    if (isSetCreateOrg())
      hashCode = hashCode * 8191 + CreateOrg.hashCode();

    hashCode = hashCode * 8191 + ((isSetCreateOrgId()) ? 131071 : 524287);
    if (isSetCreateOrgId())
      hashCode = hashCode * 8191 + CreateOrgId.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(UserInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetId()).compareTo(other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCreaterName()).compareTo(other.isSetCreaterName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreaterName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.CreaterName, other.CreaterName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCreaterId()).compareTo(other.isSetCreaterId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreaterId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.CreaterId, other.CreaterId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCreateTime()).compareTo(other.isSetCreateTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreateTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.CreateTime, other.CreateTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCreateOrg()).compareTo(other.isSetCreateOrg());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreateOrg()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.CreateOrg, other.CreateOrg);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCreateOrgId()).compareTo(other.isSetCreateOrgId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreateOrgId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.CreateOrgId, other.CreateOrgId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("UserInfo(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("CreaterName:");
    if (this.CreaterName == null) {
      sb.append("null");
    } else {
      sb.append(this.CreaterName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("CreaterId:");
    if (this.CreaterId == null) {
      sb.append("null");
    } else {
      sb.append(this.CreaterId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("CreateTime:");
    if (this.CreateTime == null) {
      sb.append("null");
    } else {
      sb.append(this.CreateTime);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("CreateOrg:");
    if (this.CreateOrg == null) {
      sb.append("null");
    } else {
      sb.append(this.CreateOrg);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("CreateOrgId:");
    if (this.CreateOrgId == null) {
      sb.append("null");
    } else {
      sb.append(this.CreateOrgId);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class UserInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public UserInfoStandardScheme getScheme() {
      return new UserInfoStandardScheme();
    }
  }

  private static class UserInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<UserInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, UserInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.id = iprot.readI64();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CREATER_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.CreaterName = iprot.readString();
              struct.setCreaterNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // CREATER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.CreaterId = iprot.readString();
              struct.setCreaterIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // CREATE_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.CreateTime = iprot.readString();
              struct.setCreateTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // CREATE_ORG
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.CreateOrg = iprot.readString();
              struct.setCreateOrgIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // CREATE_ORG_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.CreateOrgId = iprot.readString();
              struct.setCreateOrgIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, UserInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI64(struct.id);
      oprot.writeFieldEnd();
      if (struct.CreaterName != null) {
        oprot.writeFieldBegin(CREATER_NAME_FIELD_DESC);
        oprot.writeString(struct.CreaterName);
        oprot.writeFieldEnd();
      }
      if (struct.CreaterId != null) {
        oprot.writeFieldBegin(CREATER_ID_FIELD_DESC);
        oprot.writeString(struct.CreaterId);
        oprot.writeFieldEnd();
      }
      if (struct.CreateTime != null) {
        oprot.writeFieldBegin(CREATE_TIME_FIELD_DESC);
        oprot.writeString(struct.CreateTime);
        oprot.writeFieldEnd();
      }
      if (struct.CreateOrg != null) {
        oprot.writeFieldBegin(CREATE_ORG_FIELD_DESC);
        oprot.writeString(struct.CreateOrg);
        oprot.writeFieldEnd();
      }
      if (struct.CreateOrgId != null) {
        oprot.writeFieldBegin(CREATE_ORG_ID_FIELD_DESC);
        oprot.writeString(struct.CreateOrgId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class UserInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public UserInfoTupleScheme getScheme() {
      return new UserInfoTupleScheme();
    }
  }

  private static class UserInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<UserInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, UserInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetCreaterName()) {
        optionals.set(1);
      }
      if (struct.isSetCreaterId()) {
        optionals.set(2);
      }
      if (struct.isSetCreateTime()) {
        optionals.set(3);
      }
      if (struct.isSetCreateOrg()) {
        optionals.set(4);
      }
      if (struct.isSetCreateOrgId()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetId()) {
        oprot.writeI64(struct.id);
      }
      if (struct.isSetCreaterName()) {
        oprot.writeString(struct.CreaterName);
      }
      if (struct.isSetCreaterId()) {
        oprot.writeString(struct.CreaterId);
      }
      if (struct.isSetCreateTime()) {
        oprot.writeString(struct.CreateTime);
      }
      if (struct.isSetCreateOrg()) {
        oprot.writeString(struct.CreateOrg);
      }
      if (struct.isSetCreateOrgId()) {
        oprot.writeString(struct.CreateOrgId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, UserInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        struct.id = iprot.readI64();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.CreaterName = iprot.readString();
        struct.setCreaterNameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.CreaterId = iprot.readString();
        struct.setCreaterIdIsSet(true);
      }
      if (incoming.get(3)) {
        struct.CreateTime = iprot.readString();
        struct.setCreateTimeIsSet(true);
      }
      if (incoming.get(4)) {
        struct.CreateOrg = iprot.readString();
        struct.setCreateOrgIsSet(true);
      }
      if (incoming.get(5)) {
        struct.CreateOrgId = iprot.readString();
        struct.setCreateOrgIdIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

